/**
 * Generates src/types/database.ts from the live schema.
 *
 *   npm run db:types
 *
 * Uses --project-id, which goes through Supabase's Management API. The
 * --db-url form shells out to Docker to run the generator in a container, and
 * there is no Docker on this machine.
 *
 * That means the CLI has to be authenticated once, interactively:
 *
 *   npx supabase login
 *
 * It opens a browser, and the token is stored in your user profile — nothing
 * to paste around or commit.
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

import dotenv from "dotenv";

const root = path.resolve(import.meta.dirname, "..");
dotenv.config({ path: path.join(root, ".env.local"), quiet: true });

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
if (!url) {
  console.error("NEXT_PUBLIC_SUPABASE_URL is not set in .env.local");
  process.exit(1);
}

// https://<ref>.supabase.co -> <ref>
const projectRef = new URL(url).hostname.split(".")[0];
const output = path.join(root, "src", "types", "database.ts");

console.log(`Generating types for project ${projectRef}...`);

let types;
try {
  // shell:true is required on Windows — recent Node refuses to spawn a .cmd
  // shim directly. projectRef comes from a URL hostname, so it is [a-z0-9]+.
  types = execFileSync(
    "npx",
    ["supabase", "gen", "types", "typescript", "--project-id", projectRef],
    {
      cwd: root,
      encoding: "utf8",
      maxBuffer: 32 * 1024 * 1024,
      stdio: ["ignore", "pipe", "pipe"],
      shell: true,
    },
  );
} catch (error) {
  const detail = `${error.stderr ?? ""}${error.stdout ?? ""}`;
  if (/access token|not logged in|Unauthorized|login/i.test(detail)) {
    console.error(
      "\nThe Supabase CLI is not authenticated. Run this once, then retry:\n\n" +
        "  npx supabase login\n\n" +
        "It opens a browser; the token is stored in your user profile.\n",
    );
  } else {
    console.error(detail.trim() || error.message);
  }
  process.exit(1);
}

mkdirSync(path.dirname(output), { recursive: true });
writeFileSync(
  output,
  `// Generated by \`npm run db:types\`. Do not edit by hand.\n${types}`,
  "utf8",
);

console.log(`Wrote src/types/database.ts (${types.split("\n").length} lines)`);
